apiVersion: v1
kind: Service
metadata:
  name: {{ template "core.name" . }}-svc
    {{- include "core.labels" . | nindent 2 }}
    app: {{ template "core.name" . }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: django-server
  selector:
    name: {{ template "core.name" . }}
    component: app
    release: {{ .Release.Name }}
