apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "core.name" . }}-backend
  {{- include "core.labels" . | nindent 2 }}
    app: {{ template "core.name" . }}
spec:
  {{- include "core.selector" . | nindent 2 }}
      name: {{ template "core.name" . }}
      component: app
  template:
    {{- include "core.metadata" . | nindent 4 }}
        name: {{ template "core.name" . }}
        component: app
    spec:
      containers:       
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.backendRepository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        {{- include "core.envFrom" . | nindent 8 }}
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
