version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - database
    restart: always
    

    
  database:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=django_db
    ports:
      - 5432:5432

  