{{ $app_name := env "APP_NAME" | default "core"}}


repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: postgresql
  namespace: {{ $app_name }}
  chart: bitnami/postgresql
  version: "12.1.2"
  values:
  - values/staging/db/values.yaml
