{{ $app_name := env "APP_NAME" | default "core"}}


repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: postgresql
  namespace: {{ $app_name }}
  chart: bitnami/postgresql
  version: "12.1.2"
  values:
  - values/staging/db/values.yaml

- name: prometheus
  namespace: {{ $app_name }}
  chart: prometheus-community/prometheus
  version: 25.16.0
  values:
  - values/staging/prometheus/values.yaml