{{ $app_name := env "APP_NAME" | default "core"}}


repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: traefik
  url: https://traefik.github.io/charts

releases:
- name: postgresql
  namespace: {{ $app_name }}
  chart: bitnami/postgresql
  version: "12.1.2"
  values:
  - values/staging/db/values.yaml

- name: prometheus
  namespace: monitoring
  chart: prometheus-community/prometheus
  version: 25.16.0
  values:
  - values/staging/prometheus/values.yaml

- name: grafana
  namespace: monitoring
  chart: grafana/grafana
  version: 7.3.6
  values:
  - values/staging/grafana/values.yaml

- name: traefik
  namespace: traefik
  chart: traefik/traefik
  version: "26.1.0"
  values: 
  - values/staging/traefik/values.yaml
